version: 2
jobs:
    build:
        docker:
            - image: hikalium/liumos-builder:v20210115_022730
        steps:
            - checkout
            - run:
                name: Deploy prebuilt
                command: make prebuilt
            - run:
                name: Run unit test
                command: make test
            - run:
                name: Build LIUMOS.ELF
                command: make
