[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[build]
target = "x86_64-unknown-uefi"

[target.'cfg(target_os = "uefi")']
runner = "scripts/test_runner.sh"
